# Generated by Django 3.0.2 on 2020-04-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theTeam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='theteam',
            name='image',
        ),
    ]
