# Generated by Django 3.0.2 on 2020-08-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theTeam', '0002_auto_20200403_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theteam',
            name='firstname',
        ),
        migrations.AddField(
            model_name='theteam',
            name='fullname',
            field=models.CharField(blank=True, max_length=520),
        ),
    ]
