# Generated by Django 3.0.2 on 2020-08-15 08:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theTeam', '0003_auto_20200811_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamImages',
        ),
        migrations.AddField(
            model_name='theteam',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theteam',
            name='firstname',
            field=models.CharField(default='hallow name', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theteam',
            name='nt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theteam',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='theteam',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
