# Generated by Django 3.0.2 on 2020-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theTeam', '0005_theteam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theteam',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
