# Generated by Django 3.0.2 on 2020-01-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('Subject', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=5000)),
            ],
        ),
    ]
