# Generated by Django 3.0.2 on 2020-08-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_added',
        ),
    ]
