# Generated by Django 3.0.2 on 2020-08-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
