# Generated by Django 3.0.2 on 2020-08-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200816_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fullname',
            field=models.CharField(default='denno', max_length=120),
            preserve_default=False,
        ),
    ]
